name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'

  push:
    branches:
      - main
    paths:
      - 'web/**'


jobs:

  test:
    name: 'Run unit tests on code'
    defaults:
      run:
        shell: bash
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: npm install 

      - name: 'Run Tests'
        run: npm run test
        
  

